#使用代理去获取代理IP
proxy:
  host: 127.0.0.1
  port: 10809

auth:
  user: abcde
  pass: qwert

#配置信息
config:
  #监听IP
  ip: 0.0.0.0
  #webApi监听端口
  port: 80
  #http隧道代理端口
  httpTunnelPort: 8080
  #可用IP数量小于‘proxyNum’时就去抓取
  proxyNum: 10
  #代理IP验证间隔秒
  verifyTime: 300
  #抓取/检测状态线程数
  threadNum: 10000
